#!/bin/bash

# QUESTO SCRIPT COPIA IN LOCALE LA CONFIGURAZIONE RUNNING DELLO SWITCH (running-config), CHIEDE L'INSERIMENTO DI UN NUOVO DEFAULT GATEWAY , FA UNA COPIA E INVIA TRAMITE scp IL FILE MODIFICATO ALLO SWITCH SOVRASCRIVENDO IL FILE (running-config) ORIGINALE
# SCRIPT PRECONFIGURATO PER CONNESSIONE scp ALLO SWITCH csw001 CON UTENTE user

# PER ESEGUIRE LO SCRIPT BISOGNA ABILITARE LA CONFIGURAZIONE (config)file prompt quiet SULLO SWITCH
# PER ESEGUIRE LO SCRIPT BISOGNA INSTALLARE IL PACCHETTO sshpass
# PER ESEGUIRE LO SCRIPT ssh E scp DEVONO ESSERE ABILITATI SULLO SWITCH
# ALCUNI SWITCH RICHIEDONO L'ABILITAZIONE (A LIVELLO CLIENT) DEL METODO DI SCAMBIO CHIAVI diffie-hellman



# IMPOSTARE IP O HOSTNAME DEL NODO SUL QUALE CI SI VUOLE COLLEGARE IN ssh
REMOTE_HOSTNAME=csw001

# IMPOSTARE UN UTENTE DELLO SWITCH CON PREABILITAZIONI ALLA CONNESSIONE ssh
REMOTE_USERNAME=user

# IMPOSTARE LA PASSWORD DI AUTENTICAZIONE ALLO SWITCH
REMOTE_PASSWORD=password

# IMPOSTARE UN PERCORSO LOCALE NEL QUALE SALVARE I BACKUP
LOCAL_TEMP_DIRECTORY=/home/user/temp/csw001



# ESEGUE LA COPIA DEL FILE startup-config SULLA DIRECTOTY LOCALE TRAMITE scp
sshpass -p $REMOTE_PASSWORD scp $REMOTE_USERNAME@$REMOTE_HOSTNAME:"system:/running-config" $LOCAL_TEMP_DIRECTORY/running-config-previous-version

# MOSTRA UN MESSAGGIO IN CUI VIENE CHIESTO DI INSERIRE IL NUOVO DEFAULT GATEWAY
read -p "Inserire il nuovo indirizzo IP del Default Gateway (PREMERE ^C PER ANNULLARE): " NEW_GATEWAY

# DUPLICA IL FILE running-config
cp $LOCAL_TEMP_DIRECTORY/running-config-previous-version $LOCAL_TEMP_DIRECTORY/running-config

# LEGGE IL FILE TEMPORANEO running-config ESTRAPOLANDO L'IP DEL DEFAULT GATEWAY E CREA LA VARIABILE OLD_GATEWAY
sed -i 's|^ip default-gateway .*|ip default-gateway '"$NEW_GATEWAY"'|g' $LOCAL_TEMP_DIRECTORY/running-config

# ESEGUE LA COPIA DEL FILE LOCALE running-config SULLA DIRECTOTY REMOTA system:/ TRAMITE scp
sshpass -p $REMOTE_PASSWORD scp $LOCAL_TEMP_DIRECTORY/running-config $REMOTE_USERNAME@$REMOTE_HOSTNAME:"system:/running-config"

# RIMUOVE IL DUPLICATO LOCALE CONSERVANDO IL FILE running-config-previous-version CON LA CONFIGURAZIONE PRECEDENTE IN CASO DI RIPRISTINO
rm $LOCAL_TEMP_DIRECTORY/running-config




