#!/bin/bash

# QUESTO SCRIPT CREA UN NUOVO UTENTE SULLO SWITCH TRAMITE L'ESECUZIONE DI COMANDI VIA telnet
# SCRIPT PRECONFIGURATO PER CONNESSIONE telnet ALLO SWITCH csw001 CON UTENTE user

# PER ESEGUIRE LO SCRIPT BISOGNA ABILITARE LA CONFIGURAZIONE (config)file prompt quiet SULLO SWITCH
# PER ESEGUIRE LO SCRIPT BISOGNA ABILITARE telnet SULLO SWITCH



# IMPOSTARE UN IP O UN HOSTNAME DEL NODO SUL QUALE CI SI VUOLE COLLEGARE CON telnet
REMOTE_HOSTNAME=csw001

# IMPOSTARE UN UTENTE REMOTO CON PREABILITAZIONI ALLA CONNESSIONE telnet
REMOTE_USERNAME=user

# IMPOSTARE LA PASSWORD DI AUTENTICAZIONE ALLO SWITCH
REMOTE_PASSWORD=password



# IMPOSTARE I PARAMETRI DI CONFIGURAZIONE PER IL NUOVO UTENTE
# USERNAME
REMOTE_NEW_USERNAME=new_user

# PASSWORD
REMOTE_NEW_PASSWORD=new_password



(

echo $REMOTE_USERNAME

echo $REMOTE_PASSWORD

echo "configure terminal"
sleep 1

# IMPOSTA UTENTE E PASSWORD
echo "username $REMOTE_NEW_USERNAME priv 15 pass $REMOTE_NEW_PASSWORD"
sleep 1

echo "do wr"
sleep 1

echo "exit"
sleep 1

# CHIUDE CONNESSIONE
echo "exit"
sleep 1

) | telnet $REMOTE_HOSTNAME



# FINE SCRIPT
